services:
  redis:
    image: redis:8.6.0-alpine
    container_name: app-redis
    restart: always
    command: redis-server --save 60 1000 --loglevel notice --maxmemory 8gb --maxmemory-policy allkeys-lru
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
